

apiVersion: apps/v1
kind: Deployment
metadata:
  name: goals-service
  namespace: trissect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goals-service
  template:
    metadata:
      labels:
        app: goals-service
    spec:
      containers:
      - env:
        - name: MY_VARIABLE
          value: my-value
        image: docker.pkg.github.com/tuuturu/trissect-goal-service/trissect-goals-service:v0.0.8
        name: goals-service

