/*
 * Trissect Goal Service
 *
 * Handles CRUD operations on Goal resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/tuuturu/trissect-goal-service/pkg/core"
	"log"
)

func main() {
	log.Printf("Server started")

	router := core.NewRouter()

	log.Fatal(router.Run(":8080"))
}
