/*
 * Trissect Goal Service
 *
 * Handles CRUD operations on Goal resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"log"

	"github.com/tuuturu/trissect-goal-service/pkg/core"
)

func main() {
	log.Printf("Server started")

	cfg := core.LoadConfig()

	if err := cfg.Validate(); err != nil {
		panic(err)
	}

	router := core.NewRouter()

	log.Fatal(router.Run(fmt.Sprintf(":%s", cfg.Port)))
}
