/*
 * Trissect Goal Service
 *
 * Handles CRUD operations on Goal resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// DeleteGoal - 
func DeleteGoal(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetGoal - 
func GetGoal(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UpdateGoal - 
func UpdateGoal(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
