/*
 * Trissect Goal Service
 *
 * Handles CRUD operations on Goal resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AddGoal - 
func AddGoal(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetAllGoals - 
func GetAllGoals(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
