/*
 * Trissect Goal Service
 *
 * Handles CRUD operations on Goal resources
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Goal struct {
	Id     string `json:"id,omitempty" db:"id"`
	Author string `json:"author,omitempty" db:"author"`

	Parent string `json:"parent,omitempty" db:"parent"`

	Title string `json:"title" db:"title"`

	Reasoning string `json:"reasoning,omitempty" db:"reasoning"`

	Complete bool `json:"complete,omitempty" db:"complete"`
}
